safe: false

# build settings
markdown: kramdown
# markdown: redcarpet
highlighter: rouge
lsi: false
permalink: /:title

title: "Harbin"
description: "Well, happy finding you here."
baseurl: ""
url: "http://www.harbinfate.com" # replace by your site's url
twitter_username: SayHarbin
github_username:  HarbinZhang # (your name)
accent: "#f7f7e6" # accent color for blog column

author: "Harbin"
address: "Ann Arbor, Michigan"
email: "seashore.real@gmail.com"

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en

# exclude files
exclude:
  - LICENSE
  - README.md
